<?xml version="1.0" encoding="utf-8"?><Database Name="QLBH" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=QLBH;Integrated Security=True" SettingsObjectName="WindowsFormsApp9.Properties.Settings" SettingsPropertyName="QLBHConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CTHD" Member="CTHDs">
    <Type Name="CTHD">
      <Column Name="MaHoaDon" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaMonAn" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DonGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HoaDon_CTHD" Member="HoaDon" ThisKey="MaHoaDon" OtherKey="MaHoaDon" Type="HoaDon" IsForeignKey="true" />
      <Association Name="MonAn_CTHD" Member="MonAn" ThisKey="MaMonAn" OtherKey="MaMonAn" Type="MonAn" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.HoaDon" Member="HoaDons">
    <Type Name="HoaDon">
      <Column Name="MaHoaDon" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaNV" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="NgayHoaDon" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="HoaDon_CTHD" Member="CTHDs" ThisKey="MaHoaDon" OtherKey="MaHoaDon" Type="CTHD" />
      <Association Name="NV_HoaDon" Member="NV" ThisKey="MaNV" OtherKey="MaNV" Type="NV" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoaiMonAn" Member="LoaiMonAns">
    <Type Name="LoaiMonAn">
      <Column Name="MaLoaiMonAn" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenLoaiMonAn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="LoaiMonAn_MonAn" Member="MonAns" ThisKey="MaLoaiMonAn" OtherKey="MaLoaiMonAn" Type="MonAn" />
    </Type>
  </Table>
  <Table Name="dbo.MonAn" Member="MonAns">
    <Type Name="MonAn">
      <Column Name="MaMonAn" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenMonAn" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MaLoaiMonAn" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="MonAn_CTHD" Member="CTHDs" ThisKey="MaMonAn" OtherKey="MaMonAn" Type="CTHD" />
      <Association Name="LoaiMonAn_MonAn" Member="LoaiMonAn" ThisKey="MaLoaiMonAn" OtherKey="MaLoaiMonAn" Type="LoaiMonAn" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NV" Member="NVs">
    <Type Name="NV">
      <Column Name="MaNV" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NamSinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="NCL" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Luong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="NV_HoaDon" Member="HoaDons" ThisKey="MaNV" OtherKey="MaNV" Type="HoaDon" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="TenTaiKhoan" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="HovaTen" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ChucVu" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>